### ISSUE TITLE
Adding keyboard input

### ISSUE THREAD

**Issue by agastya3636** [agastya3636/calculator_using_htmlcssjs#1]
In this i want to add keyboard input also

**Comment by Vayras** [comment]
@agastya3636 Can you please assign me this issue?

**Comment by agastya3636** [comment]
Ok but please solve fast

**Comment by Vayras** [comment]
@agastya3636 
created the pull request

**Comment by agastya3636** [comment]
hi it is not working properly

**Comment by ayushflows** [comment]
Please Assign me this issue i can fix that

**Comment by ayushflows** [comment]
now  review my pull request so that i can work on it
